# Generated by Django 4.1.4 on 2022-12-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=200)),
                ('titulo_del_proyecto', models.CharField(max_length=200)),
                ('descripción_del_proyecto', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('url_de_github', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
    ]
