# Generated by Django 4.1.4 on 2022-12-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreacionProyecto',
            new_name='CrearProyecto',
        ),
    ]
